---
- name: Add Windows VM to Tower Inventory
  tower_host:
    name: "{{ windows_vm_hostname }}"
    description: "Add VM to Tower Inventory"
    inventory: "{{ tower_inventory_name }}"
    state: present
    tower_verify_ssl: no
    variables: |+
      ---
      ansible_host: "{{ windows_vm_ip }}"
      ansible_connection: winrm
      ansible_port: 5986
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_transport: credssp
- name: Sending notification email
  mail:
    host: localhost
    port: 25
    to: Sanjar Farhad <ahmadsanjar.farhad@gmail.com>
    subject: Ansible-report
    body: "{{ windows_vm_hostname }} has been added to AWX Tower Inventory"
  delegate_to: localhost
