---
- name: Clone a VM from a template
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Clean VM
      community.vmware.vmware_guest:
        validate_certs: false
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "cloned_vm_from_vm_cluster"
        datacenter: "{{ datacenter }}"
        state: absent
      register: delete_instant_clone_from_vm_when_cluster
      ignore_errors: true
      delegate_to: localhost
