---
- name: Clone a VM from a template
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Instant Clone a VM
      community.vmware.vmware_guest_instant_clone:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        folder: "{{ folder }}"
        datastore: "{{ datastore }}"
        datacenter: "{{ datacenter }}"
#        host: "{{ host }}"
        name: "{{ Clone_vm }}"
        parent_vm: "{{ parent_vm }}"
        resource_pool: "{{ resource_pool }}"
      register: vm_clone
      delegate_to: localhost
