---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Create a virtual machine from a template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ vcenter_datacenter }}"
      cluster: "{{ vcenter_vm_cluster }}"
      folder: "{{ vcenter_vm_folder }}"
      name: "{{ vmName }}"
      state: poweredon
      template: "{{ vmTemplate }}"
      customization:
        runonce:
        - powershell.exe Get-NetConnectionProfile -InterfaceAlias Ethernet0 | Set-NetConnectionProfile -NetworkCategory Private
        autologon: true
        autologoncount: 1
        existing_vm: True
        dns_servers: "{{ dns_server_list }}"
        dns_suffix: "{{ dns_suffixes }}"
        domain: "{{ domain_name }}"
        hostname: "{{ vmName }}"
        password: "{{ local_admin_password }}"
        timezone: 110
      networks:
      - name: "{{ vcenter_network_name }}"
        ip: "{{ VMIP }}"
        netmask: "255.255.255.0" 
        gateway: "{{ gateway }}"
      wait_for_ip_address: yes
      wait_for_customization: yes
    register: newvm
    
  - set_stats:
      data:
        demovmuuid: "{{ newvm.instance.hw_product_uuid }}"
