---
- name: Initiate and Format Disks
  hosts: localhost
  gather_facts: yes
  collections:
    - community.windows
  tasks:
  - name: initialize disks
    win_shell: "Initialize-Disk -Number {{ disk_number }}"
  
  - name: partition disk
    win_shell: "New-Partition -DiskNumber {{ disk_number }} -UseMaximumSize -DriveLetter {{ drive_letter }}"
    
  - name: format disk
    win_shell: "Format-Volume -DriveLetter {{ drive_letter }} -NewFileSystemLabel {{ drive_label }}"
