---
- name: Initiate and Format Disks
  hosts: all
  gather_facts: yes
  collections:
    - community.windows
  tasks:
  - name: initialize disks
    win_shell: "Initialize-Disk -Number {{ disk_number1 }}"
    win_shell: "Initialize-Disk -Number {{ disk_number2 }}"
  
  - name: partition disk
    win_shell: "New-Partition -DiskNumber {{ disk_number1 }} -UseMaximumSize -DriveLetter1 {{ drive_letter1 }}"
    win_shell: "New-Partition -DiskNumber {{ disk_number2 }} -UseMaximumSize -DriveLetter2 {{ drive_letter2 }}"
    
  - name: format disk
    win_shell: "Format-Volume -DriveLetter {{ drive_letter1 }} -NewFileSystemLabel {{ drive_label1 }}"
    win_shell: "Format-Volume -DriveLetter {{ drive_letter2 }} -NewFileSystemLabel {{ drive_label2 }}"
