---
- name: Remove a VM
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:    
  - name: Remove a VM
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ vm_Name }}"
      state: absent
#     delegate_to: localhost
    register: facts
