---
- name: Install Telnet and check SQL
  hosts: all
  tasks:  
  - name: create windows users
    win_user:
      name: Ansible
      password: "{{ ansible_pw }}"
      state: present
      groups: 
        - Users  
        
 # - name: Ensure user Ansible is present
 ### ansible.windows.win_user:
   # name: Ansible
   # password: "{{ ansible_pw }}"
   # state: present
   # groups:
   #   - Users
