---
- name: Add disks to virtual machine using UUID
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.vmware
  tasks:
  - name: Add disks to virtual machine using UUID
    community.vmware.vmware_guest_disk:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      uuid: "{{ vm_uuid }}"
      disk:
        - size_gb: "{{ vm_disk2_gb }}"
          type: "{{ vm_disk_type }}"
          datastore: "{{ vm_disk_datastore }}"
          state: present
          scsi_controller: "{{ vm_disk_scsi_controller }}"
          unit_number: "{{ vm_disk_scsi_unit }}"
          scsi_type: "{{ vm_disk_scsi_type }}"
          disk_mode: "{{ vm_disk_mode }}"
        - size_gb: "{{ vm_disk3_gb }}"
          type: "{{ vm_disk_type }}"
          datastore: "{{ vm_disk_datastore }}"
          state: present
          scsi_controller: "{{ vm_disk_scsi_controller }}"
          unit_number: "{{ vm_disk_scsi_unit }}"
          scsi_type: "{{ vm_disk_scsi_type }}"
          disk_mode: "{{ vm_disk_mode }}"
    delegate_to: localhost
    register: disk_facts
