---
- name: Install Roles, Features etc.
  hosts: all
  tasks:  
  - name: create windows users
    win_user:
      name: Ansible
      password: "{{ ansible_pw }}"
      state: present
      groups: 
        - Users
        - Administrators
